drop table if exists extension CASCADE;
create table extension
(
    id        bigint generated by default as identity,
    name varchar(20),
    FlagUse     integer,
    FlagFixed integer,
    primary key (id)
);
