drop table if exists extension CASCADE;
create table extension
(
    id        bigint generated by default as identity,
    extension varchar(10),
    price     integer,
    quantity  integer,
    primary key (id)
);
